// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rhcmppstjichgyhoxgaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_fHVGIE81mSLLr7HRkD0bwA_TJWRA82d";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);